cluster.name: vmc
discovery.zen.minimum_master_nodes: 1
discovery.type: single-node
network.host: 0.0.0.0
xpack.monitoring.collection.enabled: true
xpack.watcher.enabled: true
xpack.security.enabled: true
