FROM python:3.12-slim-bullseye

ARG VMC_VERSION=1.0.2
ENV VMC_VERSION=${VMC_VERSION}
ENV VIRTUAL_ENV=/opt/venv

RUN python3 -m venv $VIRTUAL_ENV

ENV PATH="$VIRTUAL_ENV/bin:$PATH"

RUN pip install --upgrade pip==22.0.3; \
    pip install --upgrade setuptools==59.1.1; \
    pip install --no-cache-dir vmcenter==${VMC_VERSION}; \
    python3 -m vmc collectstatic --noinput --clear;

