FROM python:3.10-slim-bookworm

ARG VMC_VERSION=1.0.2
ENV VMC_VERSION=${VMC_VERSION}
ENV VIRTUAL_ENV=/opt/venv

RUN python3 -m venv $VIRTUAL_ENV

ENV PATH="$VIRTUAL_ENV/bin:$PATH"

RUN pip install --upgrade pip setuptools wheel; \
    pip install --no-cache-dir vmcenter==${VMC_VERSION}; \
    python3 -m vmc collectstatic --noinput --clear;
