name: FEED New vulnerability with HIGH availability impact
type: any
index: "cve"
alert: hivealerter
timestamp_field: "modified_date"
filter:
- term:
    availability_impact_v3: "HIGH"
hive_connection:
  hive_host: http://hive
  hive_port: 9000
  hive_apikey: "nzZE50t3YUDyg+OgSSfbxLFAbRaa9cvt"
hive_alert_config:
  title: 'FEED New vulnerability with HIGH availability impact'
  type: 'external'
  source: 'VMC'
  description: '{match[summary]}'
  severity: 1
  tags: ['New vulnerability', '{match[id]}', '{match[base_score_v2]}']
  tlp: 1
  status: 'New'