name: Host with high vulnerability scorev2
type: any
index: "vulnerability"
alert: hivealerter
timestamp_field: "modified_date"
filter:
- range:
    cve.base_score_v2:
      from: 8
      to: 10
hive_connection:
  hive_host: http://hive
  hive_port: 9000
  hive_apikey: "nzZE50t3YUDyg+OgSSfbxLFAbRaa9cvt"
hive_alert_config:
  title: 'Host with high vulnerability scorev2'
  type: 'external'
  source: 'VMC'
  description: '{match[description]}'
  severity: 3
  tags: ['Host with high vulnerability', '{match[cve][id]}', '{match[asset][ip_address]}']
  tlp: 2
  status: 'New'