name: New vulnerability with available exploit
type: any
index: "vulnerability"
alert: hivealerter
timestamp_field: "modified_date"
realert:
    minutes: 0
filter:
- query:
    query_string: {query: '_exists_:cve.exploits'}

hive_connection:
  hive_host: http://hive
  hive_port: 9000
  hive_apikey: "nzZE50t3YUDyg+OgSSfbxLFAbRaa9cvt"

hive_alert_config:
  title: 'New vulnerability with available exploit'
  type: 'external'
  source: 'VMC'
  description: '{match[description]}'
  severity: 1
  tags: ['New vulnerability with available exploit', '{match[cve][id]}', '{match[asset][ip_address]}']
  tlp: 1
  status: 'New'