name: New vulnerability with available exploit
type: any
index: "vulnerability"
alert: hivealerter
timestamp_field: "modified_date"
alert_on_new_data: true
filter:
- term:
    exploit_available: "true"
hive_connection:
  hive_host: http://hive
  hive_port: 9000
  hive_apikey: "nzZE50t3YUDyg+OgSSfbxLFAbRaa9cvt"
hive_alert_config:
  title: 'Host with high vulnerability scorev2'
  type: 'external'
  source: 'VMC'
  description: '{match[description]}'
  severity: 1
  tags: ['New vulnerability with available exploit', '{match[cve][id]}', '{match[asset][ip_address]}']
  tlp: 1
  status: 'New'