name: New low vulnerability according to CVSS 2
type: any
index: "*vulnerability"
alert: hivealerter
alert_on_new_data: true
timestamp_field: "created_date"
realert:
    minutes: 0

filter:
- range:
    environmental_score_v2:
      from: 0.1
      to: 3.9


hive_alert_config:
  title: '{rule[name]}: {match[name]}'
  type: 'vmc\vulnerability'
  source: '{match[source]}'
  description: '**IP**: {match[asset][ip_address]}


                **Description**:
                {match[description]}


                **Solution**:
                {match[solution]}


                **Scan url**: {match[scan_file_url]}'
  severity: 1
  tags: ['{match[asset][tags]}', '{match[tags]}', '{match[asset][ip_address]}', '{match[tenant][0]}', 'Low vulnerability CVSS 2']
  status: 'New'

hive_observable_data_mapping:
 - ip: '{match[asset][ip_address]}'
 - business-unit: '{match[tenant][0]}'
 - url: '{match[scan_file_url]}'