name: Makefile CI

on:
  push:
  pull_request:
  schedule:
    - cron:  '0 23 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: build
      run: make
    
